version: '3.8'

services:
  backend:
    build: .
    container_name: lovecodeanyway-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./db_dev:/app/db_dev
