jwt:
  secret: "PLEASE_CHANGE_ME" # JWT 암호화 키
  access-token-expiration: 3600000  # 1시간, 개발용
  refresh-token-expiration: 604800000  # 7일, 개발용

oauth:
  kakao:
    client-id: "PLEASE_CHANGE_ME" # 카카오 REST API 키
    client-secret: "PLEASE_CHANGE_ME" # 카카오 REST API 시크릿
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao # 카카오 로그인 후 리다이렉트 URI(개발용, 배포시 수정)
